-- 1.公告表【T_ADVICE】
DROP TABLE IF EXISTS T_ADVICE;
-- 2.图片信息表【T_IMAGE】
DROP TABLE IF EXISTS T_IMAGE;
-- 3.菜单【T_MENU】
DROP TABLE IF EXISTS T_MENU;
-- 4.T_PROJECT_RESUME【T_PROJECT_RESUME】
DROP TABLE IF EXISTS T_PROJECT_RESUME;
-- 5.角色权限表【T_AUTHORITY】
DROP TABLE IF EXISTS T_AUTHORITY;
-- 6.角色表【T_ROLE】
DROP TABLE IF EXISTS T_ROLE;
-- 7.用户表【T_USER】
DROP TABLE IF EXISTS T_USER;