DROP TABLE IF EXISTS T_ADVICE;
CREATE TABLE T_ADVICE(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID(Primary)',
ADVICE_CONTENT VARCHAR(200) COMMENT 'advice content',
ADVICE_URL VARCHAR(100) COMMENT 'url',
DIVIDE VARCHAR(2) COMMENT 'divce',
INS_DATE DATETIME COMMENT 'Insert Time',
INS_USER_ID VARCHAR(20) COMMENT 'Insert User',
INS_PROGRAM VARCHAR(20) COMMENT 'Insert Program',
UPD_DATE DATETIME COMMENT 'Update Time',
UPD_USER_ID VARCHAR(20) COMMENT 'Update User',
UPD_PROGRAM VARCHAR(20) COMMENT 'Update Program',
LOCK_VERSION BIGINT COMMENT 'Update Version'
) COMMENT = 'Index Page Info';