DROP TABLE IF EXISTS T_ADVICE;
CREATE TABLE T_ADVICE(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID(Primary)',
ADVICE_CONTENT VARCHAR(200) COMMENT 'advice content',
ADVICE_URL VARCHAR(100) COMMENT 'url',
DIVIDE VARCHAR(2) COMMENT 'divce',
INS_DATE DATETIME COMMENT 'Insert Time',
INS_USER_ID VARCHAR(20) COMMENT 'Insert User',
INS_PROGRAM VARCHAR(20) COMMENT 'Insert Program',
UPD_DATE DATETIME COMMENT 'Update Time',
UPD_USER_ID VARCHAR(20) COMMENT 'Update User',
UPD_PROGRAM VARCHAR(20) COMMENT 'Update Program',
LOCK_VERSION BIGINT COMMENT 'Update Version'
) CHARACTER SET UTF8 COMMENT = 'Index Page Info';

INSERT INTO `freePj`.`t_advice` (`ID`, `ADVICE_CONTENT`, `ADVICE_URL`, `DIVIDE`, `INS_DATE`, `INS_USER_ID`, `INS_PROGRAM`, `UPD_DATE`, `UPD_USER_ID`, `UPD_PROGRAM`, `LOCK_VERSION`) VALUES ('1', 'Advice1', '#1', '', '2018-08-20 21:35:06', '', '', '2018-08-06 21:55:55', '', '', NULL);
INSERT INTO `freePj`.`t_advice` (`ID`, `ADVICE_CONTENT`, `ADVICE_URL`, `DIVIDE`, `INS_DATE`, `INS_USER_ID`, `INS_PROGRAM`, `UPD_DATE`, `UPD_USER_ID`, `UPD_PROGRAM`, `LOCK_VERSION`) VALUES ('2', 'Advice2', '#2', '', '2018-08-20 21:35:06', '', '', '2018-08-06 21:55:55', '', '', NULL);
INSERT INTO `freePj`.`t_advice` (`ID`, `ADVICE_CONTENT`, `ADVICE_URL`, `DIVIDE`, `INS_DATE`, `INS_USER_ID`, `INS_PROGRAM`, `UPD_DATE`, `UPD_USER_ID`, `UPD_PROGRAM`, `LOCK_VERSION`) VALUES ('3', 'Advice3', '#3', '', '2018-08-20 21:35:06', '', '', '2018-08-06 21:55:55', '', '', NULL);
