DROP TABLE IF EXISTS T_IMAGE;
CREATE TABLE T_IMAGE(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Id',
IMG_LOCATION_PRE VARCHAR(100) COMMENT 'Image location previous',
IMG_LOCATION_AFT VARCHAR(100) COMMENT 'Image location after(in the server)',
DIVIDE VARCHAR(2) COMMENT 'Image divide',
INS_DATE DATETIME COMMENT 'Insert Time',
INS_USER_ID VARCHAR(20) COMMENT 'Insert User',
INS_PROGRAM VARCHAR(20) COMMENT 'Insert Program',
UPD_DATE DATETIME COMMENT 'Update Time',
UPD_USER_ID VARCHAR(20) COMMENT 'Update User',
UPD_PROGRAM VARCHAR(20) COMMENT 'Update Program',
LOCK_VERSION BIGINT COMMENT 'Update Version'
) COMMENT = 'Image Location and url';