DROP TABLE IF EXISTS T_OPINION;
CREATE TABLE T_OPINION(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID(Primary)',
OPINION_CONTENT VARCHAR(1000) COMMENT 'OPINION content',
INS_DATE DATETIME COMMENT 'Insert Time',
INS_USER_ID VARCHAR(20) COMMENT 'Insert User',
INS_PROGRAM VARCHAR(20) COMMENT 'Insert Program',
UPD_DATE DATETIME COMMENT 'Update Time',
UPD_USER_ID VARCHAR(20) COMMENT 'Update User',
UPD_PROGRAM VARCHAR(20) COMMENT 'Update Program',
LOCK_VERSION BIGINT COMMENT 'Update Version'
) CHARACTER SET UTF8 COMMENT = 'OPINION';
