DROP TABLE IF EXISTS T_PROJECT_RESUME;
CREATE TABLE T_PROJECT_RESUME(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID(Primary)',
RESUME_CONTENT VARCHAR(200) COMMENT 'Project Or Business content',
RESUME_URL VARCHAR(100) COMMENT 'url',
DIVIDE VARCHAR(2) COMMENT 'divce',
INS_DATE DATETIME COMMENT 'Insert Time',
INS_USER_ID VARCHAR(20) COMMENT 'Insert User',
INS_PROGRAM VARCHAR(20) COMMENT 'Insert Program',
UPD_DATE DATETIME COMMENT 'Update Time',
UPD_USER_ID VARCHAR(20) COMMENT 'Update User',
UPD_PROGRAM VARCHAR(20) COMMENT 'Update Program',
LOCK_VERSION BIGINT COMMENT 'Update Version'
) CHARACTER SET UTF8 COMMENT = 'project Resume or Business Resume';

INSERT INTO `freePj`.`t_project_resume` (`ID`, `RESUME_CONTENT`, `RESUME_URL`, `DIVIDE`, `INS_DATE`, `INS_USER_ID`, `INS_PROGRAM`, `UPD_DATE`, `UPD_USER_ID`, `UPD_PROGRAM`, `LOCK_VERSION`) VALUES ('1', '这是一个为各路程序爱好者实验的项目!', 'Wait', '32', '2018-08-21 21:35:24', NULL, NULL, NULL, NULL, NULL, NULL);
