DROP TABLE IF EXISTS T_PROJECT_RESUME;
CREATE TABLE T_PROJECT_RESUME(
ID INT PRIMARY KEY AUTO_INCREMENT COMMENT 'ID(Primary)',
RESUME_CONTENT VARCHAR(200) COMMENT 'Project Or Business content',
RESUME_URL VARCHAR(100) COMMENT 'url',
DIVIDE VARCHAR(2) COMMENT 'divce',
INS_DATE DATETIME COMMENT 'Insert Time',
INS_USER_ID VARCHAR(20) COMMENT 'Insert User',
INS_PROGRAM VARCHAR(20) COMMENT 'Insert Program',
UPD_DATE DATETIME COMMENT 'Update Time',
UPD_USER_ID VARCHAR(20) COMMENT 'Update User',
UPD_PROGRAM VARCHAR(20) COMMENT 'Update Program',
LOCK_VERSION BIGINT COMMENT 'Update Version'
) COMMENT = 'project Resume or Business Resume';