DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE(
ROLE_ID INT PRIMARY KEY COMMENT 'Primary Key',
ROLE_NAME VARCHARACTER(50) COMMENT 'Role Name角色',
INS_DATE DATETIME COMMENT 'Insert Time',
INS_USER_ID VARCHAR(20) COMMENT 'Insert User',
INS_PROGRAM VARCHAR(20) COMMENT 'Insert Program',
UPD_DATE DATETIME COMMENT 'Update Time',
UPD_USER_ID VARCHAR(20) COMMENT 'Update User',
UPD_PROGRAM VARCHAR(20) COMMENT 'Update Program',
LOCK_VERSION BIGINT COMMENT 'Update Version'
) CHARACTER SET UTF8 COMMENT = 'User Role'

INSERT INTO `freepj`.`t_role` (`ROLE_ID`, `ROLE_NAME`, `INS_DATE`, `INS_USER_ID`, `INS_PROGRAM`, `UPD_DATE`, `UPD_USER_ID`, `UPD_PROGRAM`, `LOCK_VERSION`) VALUES ('1', '系统管理员', '2018-08-25 11:47:48', 'admin', NULL, '2018-08-25 11:47:55', 'admin', NULL, '0');
INSERT INTO `freepj`.`t_role` (`ROLE_ID`, `ROLE_NAME`, `INS_DATE`, `INS_USER_ID`, `INS_PROGRAM`, `UPD_DATE`, `UPD_USER_ID`, `UPD_PROGRAM`, `LOCK_VERSION`) VALUES ('2', '开发者', '2018-08-25 11:48:33', 'admin', NULL, '2018-08-25 11:48:21', 'admin', NULL, '0');
INSERT INTO `freepj`.`t_role` (`ROLE_ID`, `ROLE_NAME`, `INS_DATE`, `INS_USER_ID`, `INS_PROGRAM`, `UPD_DATE`, `UPD_USER_ID`, `UPD_PROGRAM`, `LOCK_VERSION`) VALUES ('3', '体验者', '2018-08-25 11:49:08', 'admin', NULL, '2018-08-25 11:49:14', 'admin', NULL, '0');
