DROP TABLE IF EXISTS T_ROLE;
CREATE TABLE T_ROLE(
ROLE_ID INT PRIMARY KEY COMMENT 'Primary Key',
ROLE_NAME VARCHARACTER(50) COMMENT 'Role Name角色',
INS_DATE DATETIME COMMENT 'Insert Time',
INS_USER_ID VARCHAR(20) COMMENT 'Insert User',
INS_PROGRAM VARCHAR(20) COMMENT 'Insert Program',
UPD_DATE DATETIME COMMENT 'Update Time',
UPD_USER_ID VARCHAR(20) COMMENT 'Update User',
UPD_PROGRAM VARCHAR(20) COMMENT 'Update Program',
LOCK_VERSION BIGINT COMMENT 'Update Version'
) CHARACTER SET UTF8 COMMENT = 'User Role'